stages:
    - build-test-docker
    - build
    - unit-test
    - functional-test

image:
  - name: libyangpush-ci
  - pull_policy: if-not-present

build:
  stage: build
  tags:
    - libyangpush
  script:
    - meson setup build
    - cd build
    - meson compile

unit-test:
  stage: unit-test
  tags:
    - libyangpush
  script:
    - meson setup build
    - cd build
    - meson test

function-test:
  stage: functional-test
  tags:
    - libyangpush
  script:
    - echo "This job will run functional tests, based on netopeer"
