stages:
    - build-test-docker
    - build
    - unit-test
    - functional-test

image:
  name: registry-eu.inhuawei.com:5050/libyangpush-ci
  entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]

build:
  stage: build
  tags:
    - libyangpush
  script:
    - meson setup build
    - cd build
    - meson compile

unit-test:
  stage: unit-test
  tags:
    - libyangpush
  script:
    - meson setup build
    - cd build
    - meson test

function-test:
  stage: functional-test
  tags:
    - libyangpush
  script:
    - echo "This job will run functional tests, based on netopeer"
