stages:
    - build-test-docker
    - build
    - unit-test
    - functional-test


build:
  image: libyangpush-ci
  stage: build
  tags:
    - libyangpush
  script:
    - meson setup build
    - cd build
    - meson compile

unit-test:
  image: libyangpush-ci
  stage: unit-test
  tags:
    - libyangpush
  script:
    - meson setup build
    - cd build
    - meson test

function-test:
  image: libyangpush-ci
  stage: functional-test
  tags:
    - libyangpush
  script:
    - echo "This job will run functional tests, based on netopeer"
