stages:
    - build-test-docker
    - build
    - unit-test
    - functional-test

build:
  stage: build
  script:
    - meson setup build
    - cd build
    - meson compile

unit-test:
  stage: unit-test
  script:
    - meson test
